export default {
  SET_ADDRESS: 'SET_ADDRESS',
  START_TYPED_SECTION: 'START_TYPED_SECTION',
  INCREMENT_TYPED_SECTION_INDEX: 'INCREMENT_TYPED_SECTION_INDEX',
  SET_TYPED_SECTION_INDEX: 'SET_TYPED_SECTION_INDEX',
  RESET_TYPED_SECTION_INDEX: 'RESET_TYPED_SECTION_INDEX'
};
