export default {
  SET_ADDRESS: 'SET_ADDRESS',

  SET_COLOR: 'SET_COLOR',

  FINISH_ADDRESS_BAR_TYPING: 'FINISH_ADDRESS_BAR_TYPING',
  FINISH_BACKGROUND_TYPING: 'FINISH_BACKGROUND_TYPING',
  INCREMENT_TYPED_SECTION_INDEX: 'INCREMENT_TYPED_SECTION_INDEX',
  SET_TYPED_SECTION_INDEX: 'SET_TYPED_SECTION_INDEX',
  RESET_TYPED_SECTION: 'RESET_TYPED_SECTION'
};
