export default {
  SET_ADDRESS: 'SET_ADDRESS',
  INCREMENT_TYPED_SECTION_INDEX: 'INCREMENT_TYPED_SECTION_INDEX',
  SET_TYPED_SECTION_INDEX: 'SET_TYPED_SECTION_INDEX',
  RESET_TYPED_SECTION_INDEX: 'RESET_TYPED_SECTION_INDEX'
};
